// U7 (plan 2026-05-25-001): scaffold-plugin generator tests.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { scaffoldPlugin, dispatchScaffold } from "./scaffold-plugin.mjs";
import { defineProductConfig } from "../../core/product-config.mjs";
import { verifyMarketplaceLockstep } from "../../core/marketplace-lockstep.mjs";

function tmp(pfx) { return fs.mkdtempSync(path.join(os.tmpdir(), pfx)); }

function fixtureConfig(overrides = {}) {
  return defineProductConfig({
    productName: "demo-product",
    skillIdPrefix: "demo",
    agentNamePrefix: "demo-",
    defaultManifestFile: "demo.install.json",
    binName: "demo-installer",
    repositoryUrl: "https://example.com/demo",
    ...overrides,
  });
}

test("scaffoldPlugin: writes the six expected files on a clean target", () => {
  const target = tmp("scaf-clean-");
  try {
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    assert.equal(r.written.length, 6);
    assert.equal(r.skipped.length, 0);
    const expected = [
      ".claude-plugin/plugin.json",
      ".claude-plugin/marketplace.json",
      ".codex-plugin/plugin.json",
      ".agents/plugins/marketplace.json",
      ".opencode/INSTALL.md",
      ".opencode/plugins/demo-product.js",
    ];
    for (const rel of expected) {
      assert.ok(fs.existsSync(path.join(target, rel)), `missing ${rel}`);
    }
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: second run without --force is a no-op (all skipped)", () => {
  const target = tmp("scaf-skip-");
  try {
    scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    assert.equal(r.written.length, 0);
    assert.equal(r.skipped.length, 6);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: force=true overwrites every file", () => {
  const target = tmp("scaf-force-");
  try {
    scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    fs.writeFileSync(path.join(target, ".claude-plugin/plugin.json"), "TAMPERED");
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1", force: true });
    assert.equal(r.written.length, 6);
    const after = fs.readFileSync(path.join(target, ".claude-plugin/plugin.json"), "utf8");
    assert.notEqual(after.trim(), "TAMPERED", "force must overwrite tampered files");
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: generated plugin.json + marketplace pass verifyMarketplaceLockstep", () => {
  const target = tmp("scaf-lock-");
  try {
    scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    const r = verifyMarketplaceLockstep([
      { path: path.join(target, ".claude-plugin/plugin.json"), expectedVersion: "0.0.1" },
      { path: path.join(target, ".codex-plugin/plugin.json"), expectedVersion: "0.0.1" },
      { path: path.join(target, ".claude-plugin/marketplace.json"), pluginName: "demo-product", expectedVersion: "0.0.1" },
    ]);
    assert.equal(r.ok, true, JSON.stringify(r.mismatches));
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: generated OpenCode entry imports nexel/adapters/opencode-plugin", () => {
  const target = tmp("scaf-entry-");
  try {
    scaffoldPlugin(fixtureConfig(), { repoRoot: target, version: "0.0.1" });
    const entry = fs.readFileSync(
      path.join(target, ".opencode/plugins/demo-product.js"),
      "utf8",
    );
    assert.match(entry, /from "nexel\/adapters\/opencode-plugin"/);
    assert.match(entry, /configureOpenCode/);
    assert.match(entry, /Generated by `<bin> scaffold`/);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: missing repositoryUrl throws CommandError with actionable message", () => {
  const target = tmp("scaf-noUrl-");
  try {
    // bypass defineProductConfig's optional shape — repositoryUrl is optional
    // at construct time but required at scaffold time (lazy validation)
    const cfg = defineProductConfig({
      productName: "x",
      skillIdPrefix: "x",
      agentNamePrefix: "x-",
      defaultManifestFile: "x.json",
      binName: "x-installer",
      // intentionally omit repositoryUrl
    });
    assert.throws(
      () => scaffoldPlugin(cfg, { repoRoot: target }),
      (e) => e.code === "ERR_INVALID_PRODUCT_CONFIG" && /repositoryUrl/.test(e.message),
    );
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: depAudit warns when downstream package.json omits nexel dep", () => {
  const target = tmp("scaf-dep-");
  try {
    // Simulate a downstream product whose package.json does NOT list nexel.
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify({
      name: "demo-product",
      version: "0.0.1",
      dependencies: { "some-other-lib": "^1.0.0" },
    }, null, 2));
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target });
    assert.equal(r.warnings.length, 1);
    assert.match(r.warnings[0], /nexel/);
    assert.match(r.warnings[0], /opencode plugin/);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: depAudit stays silent when nexel is in dependencies", () => {
  const target = tmp("scaf-dep-ok-");
  try {
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify({
      name: "demo-product",
      version: "0.0.1",
      dependencies: { nexel: "^0.7.0" },
    }, null, 2));
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target });
    assert.equal(r.warnings.length, 0);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: depAudit also accepts peerDependencies", () => {
  const target = tmp("scaf-peer-");
  try {
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify({
      name: "demo-product",
      version: "0.0.1",
      peerDependencies: { nexel: "^0.7.0" },
    }, null, 2));
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target });
    assert.equal(r.warnings.length, 0);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: depAudit:false skips the audit even when nexel is missing", () => {
  const target = tmp("scaf-noDeps-");
  try {
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify({
      name: "demo-product",
      version: "0.0.1",
    }, null, 2));
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target, depAudit: false });
    assert.equal(r.warnings.length, 0);
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("scaffoldPlugin: version defaults to targetDir package.json when present", () => {
  const target = tmp("scaf-ver-");
  try {
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify({
      name: "demo-product", version: "9.9.9",
    }, null, 2));
    const r = scaffoldPlugin(fixtureConfig(), { repoRoot: target });
    const plugin = JSON.parse(fs.readFileSync(path.join(target, ".claude-plugin/plugin.json"), "utf8"));
    assert.equal(plugin.version, "9.9.9");
    assert.ok(r); // silence unused-var lint
  } finally { fs.rmSync(target, { recursive: true, force: true }); }
});

test("dispatchScaffold: missing productConfig in ctx throws actionable CommandError", async () => {
  await assert.rejects(
    () => dispatchScaffold({}, {}),
    (e) => e.code === "ERR_ARGS" && /productConfig/.test(e.message),
  );
});

test("dispatchScaffold: --json envelope renders structured output", async () => {
  const target = tmp("scaf-disp-");
  const origStdout = process.stdout.write.bind(process.stdout);
  const captured = [];
  process.stdout.write = (s) => { captured.push(s); return true; };
  try {
    await dispatchScaffold(
      { target, json: true, force: false },
      { productConfig: fixtureConfig(), repoRoot: target },
    );
    process.stdout.write = origStdout;
    const parsed = JSON.parse(captured.join(""));
    assert.equal(parsed.written.length, 6);
    assert.equal(parsed.skipped.length, 0);
  } finally {
    process.stdout.write = origStdout;
    fs.rmSync(target, { recursive: true, force: true });
  }
});
